### ISSUE TITLE
ngcc config not correctly implemented

### ISSUE THREAD

**Issue by EvtK** [Sitecore/jss#452]
## Description
ngcc config is implemented like this:

https://github.com/Sitecore/jss/pull/370/commits/464851ee512546747fb5f29ce7bed46cf073052e

## Expected behavior
but should be implemented like this:

https://github.com/Sitecore/jss/issues/348#issuecomment-681953149

Because of the wrong implementation, ngcc compiler still produces this error:

https://github.com/angular/angular/issues/36164

## Possible Fix
Fix the implementation :)

**Comment by sc-illiakovalenko** [comment]
@EvtK  Fixed in #468. Will be released in JSS 15

**Comment by EvtK** [comment]
@sc-illiakovalenko thanks for the fix!

When will JSS 15 be released? I'm also in need of the changes that will enable the use of angular 10 :)

**Comment by sc-illiakovalenko** [comment]
@EvtK Released 1h ago :)

**Comment by EvtK** [comment]
@sc-illiakovalenko awesome, thanks a bunch for this release!

I'm afraid I have made a mistake though. The ngcc config is still not right. I contains a reference to 'packages' which shouldn't be there. I am really truly sorry for this.

The right config (I have tested this) should be:

```
module.exports = {
  entryPoints: {
    './dist': {
      ignore: true,
    },
  },
};
```

Do you want me to open up a new issue?

**Comment by sc-illiakovalenko** [comment]
@EvtK I can reopen this one

**Comment by sc-illiakovalenko** [comment]
Fixed in #484 . Will release 15.0.1

**Comment by EvtK** [comment]
awesome, thanks for the quick fix. Can confirm issue is solved now!

**Comment by sc-illiakovalenko** [comment]
@EvtK Thank you for confirmation
